### ISSUE TITLE
rockspec

### ISSUE THREAD

**Issue by Kaixhin** [facebook/MazeBase#5]
Would you consider adding a rockspec file so that the environment and games can be installed via luarocks? This would make it easier to use as a standalone component, and I would add it to [`rlenvs`](https://github.com/Kaixhin/rlenvs/tree/mazebase).

**Comment by aszlam** [comment]
Sorry for the slow reply!  We intend to do a cleanup of the code after NIPS; at that point we will add a rockspec file.

**Comment by Kaixhin** [comment]
Hi @aszlam, any update on this?

**Comment by ebetica** [comment]
Just added it with the most recent commits. The directory structure changed a little to make Mazebase into a package, check the updated readme.

**Comment by Kaixhin** [comment]
Thanks! Any way that the rockspec could be adjusted to allow installation without cloning the repo e.g. via `luarocks install https://raw.githubusercontent.com/facebook/MazeBase/master/mazebase-1.0.0-0.rockspec`?
