### ISSUE TITLE
PyTorch version

### ISSUE THREAD

**Issue by zuoxingdong** [facebook/MazeBase#8]
Is there a recent plan to convert this repo to Python that can be used for PyTorch ?

**Comment by ebetica** [comment]
I just pushed a version of MazeBase I've had internally. There's not much work on it right now, but if you like to use it, feel free to! Here's an [example](https://github.com/facebook/MazeBase/blob/master/py/example.py) of how to run it.

I can work with you if you believe there's something that's not to parity with lua/MazeBase. There's a couple API changes to make it more "pythonic" and more extensible, but we tried to make it as close to parity as possible.
